#!/usr/bin/env bash
#
# get user input
#
echo "You must be root to run this script!"
echo "And your .vimrc will be covered!"
read -p "Are you sure? [y/n]"  -n 1 anwser
echo ""

if [[ "$anwser" == "n" ]] || [[ "$anwser" == "N" ]]; then
    exit 0    
fi

#
# get vundle
#
rm -rf ~/.vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

#
# set vimrc
#
cp .vimrc ~/.

#
# copy colorscheme
#
cp -r colors ~/.vim

#
# fetch plugins
#
vim +BundleInstall +qall

#
# to do
#
echo "There is more to do:"
echo "- Beautiful Powerline"
echo "  apt-get install vim-gtk"
echo "- YCM"
echo "  cd ~/.vim/bundle/YouCompleteMe && type cmake && python install.py --clang-completer"
echo "- JavaScript YCM support"
echo "  cd ~/.vim/bundle/tern_for_vim && npm install"
